APIを変える
givery-bootcamp/dena-2024-team7 pull request #33
Opened 2024-06-25 08:38 UTC by yuya-isaka

2024-06-25 09:09 UTC, kurusunagisa approved these changes
LGTM!

2024-06-25 09:10 UTC, kurusunagisa requested changes
フロントに話すの忘れてた

2024-06-26 02:33 UTC, ing08 approved these changes
LGTM

2024-06-26 02:33 UTC, kurusunagisa approved these changes

2024-06-26 02:36 UTC, merged